// Central seed + fallback content for CEA.
// Used to populate Postgres on first run and as a graceful fallback
// if the database is unreachable during build.

export const SEED_TRAILS = [
  {
    slug: "yahi-trail",
    name: "Yahi Trail",
    parkArea: "Lower Bidwell Park",
    difficulty: "Easy" as const,
    lengthMiles: "3.2",
    elevationGainFt: 120,
    surface: "Dirt singletrack, shaded",
    description:
      "The beloved creekside trail following Big Chico Creek through Lower Park. Wide, shaded, and ideal for new riders, families, and gaited conditioning rides. Expect hikers and cyclists — CEA yield signs posted at all junctions.",
    parkingInfo:
      "One-Mile Recreation Area lot or Five-Mile (Horse Cove). Trailer parking best at Five-Mile or Horseshoe Lake staging.",
    facilities: ["Trailer parking", "Horse water", "Restrooms", "Picnic sites"],
    stagingLat: "39.7352",
    stagingLng: "-121.7831",
    status: "open" as const,
    horseWater: true,
    trailerParking: true,
    restrooms: true,
    shadeLevel: "Heavy",
    bestSeason: "Year-round",
  },
  {
    slug: "annie-bidwell-trail",
    name: "Annie Bidwell Trail",
    parkArea: "Middle Bidwell Park",
    difficulty: "Moderate" as const,
    lengthMiles: "4.6",
    elevationGainFt: 380,
    surface: "Dirt fire road + singletrack",
    description:
      "Rolling middle-park loop through oak savanna with seasonal creek crossings. A CEA favorite for group rides and the annual Spring Poker Ride. Can be slick after rain — check condition reports before hauling out.",
    parkingInfo: "Trailhead at Manzanita Ave / Day Camp area. Limited trailer turnaround.",
    facilities: ["Trailer parking", "Hitching rail", " mounting block"],
    stagingLat: "39.7445",
    stagingLng: "-121.7620",
    status: "open" as const,
    horseWater: false,
    trailerParking: true,
    restrooms: false,
    shadeLevel: "Partial",
    bestSeason: "Fall – Spring",
  },
  {
    slug: "south-rim-trail",
    name: "South Rim Trail",
    parkArea: "South Rim",
    difficulty: "Difficult" as const,
    lengthMiles: "5.8",
    elevationGainFt: 640,
    surface: "Rocky basalt, exposed",
    description:
      "High rim trail with sweeping views of the canyon and excellent winter footing. Not recommended in summer heat or for green horses — steep drop-offs and shared use with mountain bikes on weekends.",
    parkingInfo: "South Rim / Parking Lot E. Arrive before 9am on weekends.",
    facilities: ["Trailer parking", "Vista points", "No water"],
    stagingLat: "39.7520",
    stagingLng: "-121.7300",
    status: "caution" as const,
    horseWater: false,
    trailerParking: true,
    restrooms: false,
    shadeLevel: "Minimal",
    bestSeason: "Oct – Apr",
  },
  {
    slug: "north-rim-horseshoe-loop",
    name: "North Rim + Horseshoe Lake Loop",
    parkArea: "Horseshoe Lake Area",
    difficulty: "Moderate" as const,
    lengthMiles: "6.4",
    elevationGainFt: 420,
    surface: "Sandy loam, lake loop flat",
    description:
      "The classic CEA schooling loop: park at Horseshoe Lake staging, warm up on the flat lake loop, then climb the North Rim for conditioning. Horse water at the lake (seasonal) and the best trailer staging in Upper Park.",
    parkingInfo:
      "Horseshoe Lake staging — large gravel lot, room for 10+ rigs. Water spigot near restrooms.",
    facilities: ["Trailer parking", "Horse water", "Restrooms", "Hitching rail", " mounting block"],
    stagingLat: "39.7580",
    stagingLng: "-121.7050",
    status: "open" as const,
    horseWater: true,
    trailerParking: true,
    restrooms: true,
    shadeLevel: "Partial",
    bestSeason: "Year-round",
  },
  {
    slug: "upper-park-road-butte-creek",
    name: "Upper Park Road to Bear Hole",
    parkArea: "Upper Bidwell Park",
    difficulty: "Easy" as const,
    lengthMiles: "7.0",
    elevationGainFt: 200,
    surface: "Paved service road + dirt shoulders",
    description:
      "Gentle out-and-back along the canyon floor to Bear Hole swimming area. Wide shoulders make it safe for ponying young horses. Gate closures possible after storms — see reports.",
    parkingInfo: "Parking Lot P / Diversion Dam. Wide turnaround for big rigs.",
    facilities: ["Trailer parking", "Creek access", "No restrooms"],
    stagingLat: "39.7701",
    stagingLng: "-121.6880",
    status: "open" as const,
    horseWater: true,
    trailerParking: true,
    restrooms: false,
    shadeLevel: "Partial",
    bestSeason: "Spring – Fall",
  },
  {
    slug: "guardian-trail",
    name: "Guardian Trail Connector",
    parkArea: "Middle Bidwell Park",
    difficulty: "Moderate" as const,
    lengthMiles: "1.8",
    elevationGainFt: 260,
    surface: "Narrow singletrack",
    description:
      "Short connector between creek level and the rim. Technical in one rocky chute — most riders walk it. Recently cleared by the CEA trail crew (thank you, volunteers).",
    parkingInfo: "No dedicated lot — access via Yahi or Annie Bidwell.",
    facilities: ["No water", "No restrooms"],
    stagingLat: "39.7470",
    stagingLng: "-121.7500",
    status: "caution" as const,
    horseWater: false,
    trailerParking: false,
    restrooms: false,
    shadeLevel: "Heavy",
    bestSeason: "Year-round",
  },
];

export const SEED_BUSINESSES = [
  {
    slug: "bidwell-board-stable",
    name: "Bidwell Boarding Stable",
    category: "Boarding",
    description:
      "Full-care boarding 5 minutes from Upper Park with 12x12 stalls, irrigated pasture turnout, lighted arena, and direct trail access. CEA member since 2011.",
    phone: "(530) 555-0142",
    email: "hello@bidwellboarding.example",
    website: "https://example.com",
    address: "2048 Upper Park Rd",
    city: "Chico, CA",
    isMember: true,
    isFeatured: true,
    status: "approved" as const,
    services: ["Full care", "Pasture turnout", "Arena", "Trail access"],
  },
  {
    slug: "foothill-farrier",
    name: "Foothill Farrier Service — Dan Reyes",
    category: "Farrier",
    description:
      "AFA-certified farrier serving Chico, Durham & Paradise. Hot shoeing, barefoot trims, therapeutic packages. Calm with young horses.",
    phone: "(530) 555-0188",
    email: "dan@foothillfarrier.example",
    website: "",
    address: "Mobile — serves Bidwell area",
    city: "Chico, CA",
    isMember: true,
    isFeatured: true,
    status: "approved" as const,
    services: ["Hot shoeing", "Trims", "Therapeutic"],
  },
  {
    slug: "creekside-equine-vet",
    name: "Creekside Equine Veterinary",
    category: "Veterinary",
    description:
      "Ambulatory + haul-in clinic on Dayton Rd. Lameness, dentistry, repro, and 24/7 colic emergency line for established clients.",
    phone: "(530) 555-0119",
    email: "care@creeksideequine.example",
    website: "https://example.com",
    address: "4150 Dayton Rd",
    city: "Chico, CA",
    isMember: true,
    isFeatured: false,
    status: "approved" as const,
    services: ["Lameness", "Dentistry", "Emergency"],
  },
  {
    slug: "oak-savanna-training",
    name: "Oak Savanna Training — Mara Ellison",
    category: "Training",
    description:
      "Dressage-based foundation training with an emphasis on trail confidence. Monthly desensitization clinics co-hosted with CEA at Horseshoe Lake.",
    phone: "(530) 555-0160",
    email: "mara@oaksavanna.example",
    website: "https://example.com",
    address: "Durham, CA",
    city: "Durham, CA",
    isMember: true,
    isFeatured: true,
    status: "approved" as const,
    services: ["Colt starting", "Trail confidence", "Clinics"],
  },
  {
    slug: "little-bit-lessons",
    name: "Little Bit Riding Lessons",
    category: "Lessons",
    description:
      "Beginner-friendly lesson barn with quiet school horses. Youth horsemanship, adult re-rider program, and CEA youth scholarship seats.",
    phone: "(530) 555-0127",
    email: "ride@littlebit.example",
    website: "",
    address: "Nord Hwy",
    city: "Chico, CA",
    isMember: true,
    isFeatured: false,
    status: "approved" as const,
    services: ["Youth lessons", "Adult re-riders", "Camps"],
  },
  {
    slug: "sierra-tack-feed",
    name: "Sierra Tack & Feed",
    category: "Tack & Feed",
    description:
      "Family-owned since 1987. 10% off for CEA members on the first Saturday. Blanket wash, consignment tack wall, and orchard/alfalfa delivery.",
    phone: "(530) 555-0104",
    email: "shop@sierratack.example",
    website: "https://example.com",
    address: "1380 E 9th St",
    city: "Chico, CA",
    isMember: true,
    isFeatured: false,
    status: "approved" as const,
    services: ["Feed delivery", "Consignment", "Blanket wash"],
  },
  {
    slug: "north-valley-hauling",
    name: "North Valley Horse Hauling",
    category: "Hauling",
    description:
      "Insured 3-horse slant with box-stall option. Local hauls to Bidwell trailheads plus long-distance to shows and UC Davis.",
    phone: "(530) 555-0199",
    email: "haul@northvalley.example",
    website: "",
    address: "Mobile",
    city: "Chico, CA",
    isMember: false,
    isFeatured: false,
    status: "approved" as const,
    services: ["Local hauls", "Emergency haul", "Long distance"],
  },
  {
    slug: "wildwood-arena",
    name: "Wildwood Arena & Event Grounds",
    category: "Arena & Facilities",
    description:
      "120x240 lighted arena, round pens, and overnight stalls available for CEA clinic weekends. Open-ride nights every Thursday.",
    phone: "(530) 555-0133",
    email: "book@wildwoodarena.example",
    website: "https://example.com",
    address: "Wildwood area",
    city: "Chico, CA",
    isMember: true,
    isFeatured: false,
    status: "approved" as const,
    services: ["Arena rental", "Overnight stalls", "Clinics"],
  },
  {
    slug: "canyon-light-photo",
    name: "Canyon Light Photography",
    category: "Photography",
    description:
      "Equestrian portrait + event photographer. Official photographer for the CEA Poker Ride and Holiday Parade of Horses.",
    phone: "(530) 555-0171",
    email: "hello@canyonlight.example",
    website: "https://example.com",
    address: "Chico, CA",
    city: "Chico, CA",
    isMember: true,
    isFeatured: false,
    status: "approved" as const,
    services: ["Portraits", "Events", "Sales photos"],
  },
];

export const SEED_EVENTS = [
  {
    slug: "spring-poker-ride-2026",
    title: "Spring Poker Ride at Horseshoe Lake",
    description:
      "Our signature fundraiser: a marked 6-mile loop, five poker stops, lunch, and prizes for best and worst hands. Proceeds fund trail signs and mounting blocks. All paces welcome; non-riders can volunteer at stops.",
    eventType: "Ride",
    startAt: new Date("2026-04-18T09:00:00-07:00"),
    endAt: new Date("2026-04-18T14:00:00-07:00"),
    location: "Horseshoe Lake Staging, Upper Bidwell Park",
    cost: "$35 members · $45 non-members",
    capacity: 120,
    rsvpCount: 64,
    imageNote: "Placeholder: authentic photo of local riders at Horseshoe Lake start line",
    isPublished: true,
    requiresRsvp: true,
  },
  {
    slug: "desensitization-clinic-march",
    title: "Trail Confidence & Desensitization Clinic",
    description:
      "Half-day clinic with Mara Ellison: tarps, bridges, creek crossings, and bike encounters. Small groups split by experience. Auditors free. CEA youth members ride half price.",
    eventType: "Clinic",
    startAt: new Date("2026-03-14T09:30:00-07:00"),
    endAt: new Date("2026-03-14T13:00:00-07:00"),
    location: "Wildwood Arena & Event Grounds",
    cost: "$65 riders · Free auditors",
    capacity: 24,
    rsvpCount: 18,
    imageNote: "Placeholder: authentic photo of clinic groundwork session",
    isPublished: true,
    requiresRsvp: true,
  },
  {
    slug: "trail-work-day-april",
    title: "Volunteer Trail Work Day — Guardian Chute",
    description:
      "Hands + loppers needed to armor the rocky chute on Guardian Trail. No horse required. Tools, gloves, and lunch provided. Community-service hours signed.",
    eventType: "Volunteer",
    startAt: new Date("2026-04-04T08:30:00-07:00"),
    endAt: new Date("2026-04-04T12:00:00-07:00"),
    location: "Meet at Parking Lot E, South Rim",
    cost: "Free — lunch provided",
    capacity: 30,
    rsvpCount: 12,
    imageNote: "Placeholder: authentic photo of CEA trail crew volunteers",
    isPublished: true,
    requiresRsvp: true,
  },
  {
    slug: "monthly-meeting-march",
    title: "Monthly Member Meeting — Park Rangers Q&A",
    description:
      "Bidwell Park rangers join us to discuss equestrian access, gate hours, and the new wayfinding pilot. Open to all; members vote on the summer ride calendar.",
    eventType: "Meeting",
    startAt: new Date("2026-03-05T18:30:00-08:00"),
    endAt: new Date("2026-03-05T20:00:00-08:00"),
    location: "Chico Creek Nature Center, Oak Room",
    cost: "Free",
    capacity: 80,
    rsvpCount: 31,
    imageNote: "Placeholder: authentic photo of member meeting",
    isPublished: true,
    requiresRsvp: false,
  },
  {
    slug: "sunset-social-ride",
    title: "Sunset Social Ride — Yahi Trail",
    description:
      "Easy 90-minute sunset ride + potluck at Five-Mile. Great first ride for new members. Loaner helmets available; kids on leadline welcome.",
    eventType: "Social",
    startAt: new Date("2026-05-08T17:30:00-07:00"),
    endAt: new Date("2026-05-08T20:00:00-07:00"),
    location: "Five-Mile / Horse Cove",
    cost: "Free — bring a dish",
    capacity: 40,
    rsvpCount: 22,
    imageNote: "Placeholder: authentic photo of riders on Yahi at golden hour",
    isPublished: true,
    requiresRsvp: true,
  },
  {
    slug: "schooling-show-june",
    title: "Summer Schooling Show — Dressage & Trail",
    description:
      "Low-key, supportive show with dressage tests through First Level plus a judged trail course. Ribbons through 6th, high-point buckle for CEA members.",
    eventType: "Show",
    startAt: new Date("2026-06-13T08:00:00-07:00"),
    endAt: new Date("2026-06-13T16:00:00-07:00"),
    location: "Wildwood Arena & Event Grounds",
    cost: "$25/class members",
    capacity: 60,
    rsvpCount: 9,
    imageNote: "Placeholder: authentic photo of schooling show awards",
    isPublished: true,
    requiresRsvp: true,
  },
];

export const SEED_NEWS = [
  {
    slug: "guardian-chute-cleared",
    title: "Trail Crew Clears the Guardian Chute",
    excerpt:
      "Twelve volunteers, four hours, one cleared chute. Guardian Trail is rideable again — walk the rocky section until the new armoring settles.",
    body: "On Saturday, twelve CEA volunteers — plus two rangers and one very patient mule named Biscuit — cleared winter blowdown and re-armored the rocky chute on Guardian Trail.\n\nThe trail is rideable again. Please WALK the chute for the next month while the new rock settles, and report any movement via the Trail Conditions page.\n\nThank you to Sierra Tack & Feed for donating lunch and to every hand that carried rock. Our next work day is April 4 at South Rim — no horse required.",
    category: "Trail Work",
    author: "CEA Trail Committee",
    isPublished: true,
    publishedAt: new Date("2026-02-20T10:00:00-08:00"),
  },
  {
    slug: "new-wayfinding-pilot",
    title: "New Wayfinding Pilot: What Riders Need to Know",
    excerpt:
      "Bidwell Park is piloting numbered junction markers this spring. Here's how to use them — and how CEA members shaped the design.",
    body: "Starting in March, you will see small numbered markers at 14 junctions in Middle and Upper Park. Each marker has a number, a QR code, and a 'you are here' reference.\n\nWhy it matters for riders: in an emergency, give dispatch the marker number — it pinpoints your location far faster than 'somewhere on the Rim.'\n\nCEA advocated for horse-height placement and non-reflective finishes so markers won't spook horses. If a marker startles your horse or is placed poorly, tell us and we will raise it with the Park Division.",
    category: "Park Access",
    author: "CEA Board",
    isPublished: true,
    publishedAt: new Date("2026-02-10T09:00:00-08:00"),
  },
  {
    slug: "youth-scholarship-2026",
    title: "2026 Youth Horsemanship Scholarships Open",
    excerpt:
      "Four $250 scholarships for riders 8–17. Applications close March 31. Lessons, clinics, and Poker Ride entries all eligible.",
    body: "CEA is proud to open applications for the 2026 Youth Horsemanship Scholarship: four awards of $250 for riders ages 8–17.\n\nFunds can cover lessons, clinic fees, or Poker Ride entries. Applicants need a one-page letter (or a short video) about what they love about riding in Bidwell Park, plus a reference from an instructor or CEA member.\n\nApplications close March 31. Winners will be announced at the Spring Poker Ride and featured in the summer newsletter.",
    category: "Scholarships",
    author: "CEA Youth Committee",
    isPublished: true,
    publishedAt: new Date("2026-01-28T09:00:00-08:00"),
  },
  {
    slug: "winter-footing-guide",
    title: "Winter Footing Guide: Where to Ride After Rain",
    excerpt:
      "South Rim drains in hours; Annie Bidwell holds water for days. Our volunteer guide to winter footing across the park.",
    body: "After rain, footing varies dramatically across Bidwell Park. Our rule of thumb from decades of member rides:\n\n• South Rim & North Rim: rideable within 24 hours — basalt drains fast.\n• Horseshoe Lake loop: rideable in 24–48 hours; avoid the low northeast corner.\n• Annie Bidwell: give it 3–4 dry days; creek crossings stay slick.\n• Yahi Trail: shaded sections stay muddy — walk the low spots and stay on-trail to protect the tread.\n\nWhen in doubt, check Trail Conditions or post your own report. Photos of crossings help everyone.",
    category: "Riding Tips",
    author: "Mara Ellison",
    isPublished: true,
    publishedAt: new Date("2026-01-12T09:00:00-08:00"),
  },
];

export const SEED_RESOURCES = [
  {
    slug: "bidwell-equestrian-trail-map",
    title: "Bidwell Park Equestrian Trail Map",
    description:
      "Printable 2-page map with trailer staging, horse water, and junction numbers. Updated February 2026 with the wayfinding pilot.",
    category: "Trail Map",
    fileUrl: "#",
    fileType: "PDF",
    fileSize: "2.4 MB",
    downloadCount: 412,
  },
  {
    slug: "cea-bylaws-2025",
    title: "CEA Bylaws (2025)",
    description: "Current bylaws as adopted at the November 2025 general meeting.",
    category: "Governance",
    fileUrl: "#",
    fileType: "PDF",
    fileSize: "180 KB",
    downloadCount: 96,
  },
  {
    slug: "membership-form-printable",
    title: "Membership Form (printable)",
    description: "Prefer paper? Print, fill out, and mail with a check — or bring to any meeting.",
    category: "Form",
    fileUrl: "#",
    fileType: "PDF",
    fileSize: "120 KB",
    downloadCount: 188,
  },
  {
    slug: "trail-etiquette-card",
    title: "Trail Etiquette & Yield Card",
    description:
      "Wallet card covering who yields to whom, passing bikes safely, and what to do at creek crossings. Great for new riders.",
    category: "Safety",
    fileUrl: "#",
    fileType: "PDF",
    fileSize: "640 KB",
    downloadCount: 527,
  },
  {
    slug: "winter-footing-guide-pdf",
    title: "Winter Footing Guide",
    description: "One-page guide to where to ride — and where to wait — after rain.",
    category: "Guide",
    fileUrl: "#",
    fileType: "PDF",
    fileSize: "310 KB",
    downloadCount: 203,
  },
  {
    slug: "volunteer-waiver",
    title: "Volunteer Waiver & Safety Brief",
    description: "Required for trail work days. Minors need a parent signature.",
    category: "Form",
    fileUrl: "#",
    fileType: "PDF",
    fileSize: "95 KB",
    downloadCount: 74,
  },
];

export const SEED_REPORTS = [
  {
    reporterName: "J. Alvarez (member)",
    condition: "good",
    hazardType: "",
    description:
      "Yahi is in great shape end to end. One muddy patch near mile 2 — easily walked around. Creek crossing ankle-deep.",
    locationDetail: "Mile 2, north of Five-Mile",
    status: "approved" as const,
    trailSlug: "yahi-trail",
  },
  {
    reporterName: "S. Park (member)",
    condition: "fair",
    hazardType: "",
    description:
      "South Rim rideable but windy with loose rock on the descent. Recommend boots — basalt is sharp after the rain.",
    locationDetail: "Rim descent, east section",
    status: "approved" as const,
    trailSlug: "south-rim-trail",
  },
  {
    reporterName: "R. Chen (volunteer)",
    condition: "hazard",
    hazardType: "Downed tree",
    description:
      "Oak limb blocking 3/4 of tread on Guardian chute. Passable on foot leading, not safe to ride through. Flagged with orange tape.",
    locationDetail: "Guardian chute, mid-slope",
    status: "approved" as const,
    trailSlug: "guardian-trail",
  },
];
